"""Hand-maintained seed list of known disposable email services.

Each entry is the canonical primary domain. Many services rotate frontend
domains, which is exactly the problem this project solves; the rotated
domains get picked up via community lists and MX fingerprinting.
"""

SEED_DOMAINS: list[str] = [
    "mailinator.com",
    "guerrillamail.com",
    "sharklasers.com",
    "grr.la",
    "guerrillamailblock.com",
    "spam4.me",
    "pokemail.net",
    "yopmail.com",
    "yopmail.fr",
    "yopmail.net",
    "tempmail.com",
    "temp-mail.org",
    "temp-mail.io",
    "10minutemail.com",
    "10minutemail.net",
    "10minutemail.org",
    "dispostable.com",
    "dropmail.me",
    "10mail.org",
    "maildrop.cc",
    "mintemail.com",
    "mohmal.com",
    "fakemailgenerator.com",
    "throwawaymail.com",
    "trashmail.com",
    "trashmail.de",
    "tempmailaddress.com",
    "tempinbox.com",
    "tempr.email",
    "fakeinbox.com",
    "getairmail.com",
    "mailcatch.com",
    "mailnesia.com",
    "spambog.com",
    "spamgourmet.com",
    "spamex.com",
    "owlymail.com",
    "minuteinbox.com",
    "moakt.com",
    "anonbox.net",
    "deadaddress.com",
    "mytrashmail.com",
    "incognitomail.org",
    "jetable.org",
    "mailexpire.com",
    "meltmail.com",
    "tempemail.net",
    "tempemail.co",
    "throwam.com",
    "wegwerfmail.de",
    "anonymbox.com",
]
