"""Sync the canonical /data files into the publishable packages.

The pip package reads its bundled data files at import time. The npm package
embeds the data as a generated TypeScript module so it has no runtime fs/JSON
parsing cost and works in browser bundlers.

Run this whenever data/ changes before publishing.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "data"
PY_DATA = REPO / "packages" / "python" / "src" / "burner_radar_data" / "data"
NPM_SRC = REPO / "packages" / "npm" / "src"


def sync_python() -> None:
    PY_DATA.mkdir(parents=True, exist_ok=True)
    for name in ("domains.txt", "services.json"):
        shutil.copy2(DATA / name, PY_DATA / name)
    print(f"[ok] python: synced domains.txt and services.json")


def sync_npm() -> None:
    domains = [
        line for line in (DATA / "domains.txt").read_text(encoding="utf-8").splitlines() if line
    ]
    services_payload = json.loads((DATA / "services.json").read_text(encoding="utf-8"))
    generated_at = services_payload.get("generated_at", "")

    # Compact array literals keep the generated file small enough for bundlers.
    domains_literal = "[" + ",".join(json.dumps(d) for d in domains) + "]"

    service_pairs: list[tuple[str, str]] = []
    services_obj: dict[str, list[str]] = {}
    for entry in services_payload.get("services", []):
        svc = entry["service"]
        ds = list(entry.get("domains", []))
        services_obj[svc] = ds
        for d in ds:
            service_pairs.append((d, svc))
    pairs_literal = (
        "[" + ",".join(f"[{json.dumps(d)},{json.dumps(s)}]" for d, s in service_pairs) + "]"
    )
    services_obj_literal = json.dumps(services_obj)

    NPM_SRC.mkdir(parents=True, exist_ok=True)
    out = NPM_SRC / "data.ts"
    out.write_text(
        "// Generated by scripts/sync_packages.py. Do not edit by hand.\n"
        "/* eslint-disable */\n\n"
        f'export const VERSION = "0.1.0";\n'
        f'export const GENERATED_AT = {json.dumps(generated_at)};\n\n'
        f"export const DOMAINS: ReadonlySet<string> = new Set({domains_literal});\n\n"
        f"export const SERVICE_BY_DOMAIN: ReadonlyMap<string, string> = new Map({pairs_literal});\n\n"
        f"export const SERVICES: Readonly<Record<string, readonly string[]>> = "
        f"Object.freeze({services_obj_literal});\n",
        encoding="utf-8",
    )
    print(f"[ok] npm: wrote {out.relative_to(REPO)} ({out.stat().st_size // 1024} KB)")


def main() -> int:
    if not (DATA / "domains.txt").exists():
        print("[err] data/domains.txt not found. Run `python -m burner_radar build` first.", file=sys.stderr)
        return 1
    sync_python()
    sync_npm()
    return 0


if __name__ == "__main__":
    sys.exit(main())
